#!/usr/bin/env php
<?php
define('FLARUM_START', microtime(true));

require __DIR__ . '/vendor/autoload.php';

$server = new Flarum\Console\Server(__DIR__, __DIR__ . '/public');
$server->setConfig(require __DIR__ . '/config/app.php');
$server->listen();
